name: Release Notes
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance & Refactoring
      labels:
        - refactor
        - chore
    - title: 📝 Documentation
      labels:
        - documentation
        - docs
    - title: 📦 Dependency Updates
      labels:
        - dependencies
