name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v', e.g., v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release for win-x64
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -o ./publish

      - name: Create Zip Archive
        run: Compress-Archive -Path ./publish/* -DestinationPath CueComplete-win-x64.zip
        shell: pwsh

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: CueComplete-win-x64.zip
          body: ${{ steps.changelog.outputs.changes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
